tf = sc.textFile("D:\INSOFE\Big Data\Projects\NGrams\Dataset\w3_.txt")
tf.top(5)
w = tf.map(lambda l: l.split('\t')).map(lambda l: l[1]+" "+l[0]+","+l[2]+" "+l[0]+","+l[3]+" "+l[0]).flatMap(lambda l: l.split(',')).map(lambda l: l.split(' ')).map(lambda l: (l[0],l[1]))
df = w.toDF()
df.show(5)
df = df.select(df["_1"].alias("word"), df["_2"].alias("count"))
df.printSchema()
